version: '3.2'

services:
  gpio:
    image: jgivoni/rpi-gpio-server:3-dev
    container_name: gpio
    privileged: true # Needed for PWM
    command: ["nodemon", "server.js"]
    volumes:
      - .:/usr/src/app
    ports:
      - 7695:7695
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
