version: '3.2'

services:
  waterpi:
    image: waterpi:latest
    build: .
    volumes:
    - type: bind
      source: .
      target: /usr/src/app
    links:
    - gpio
#    command: php ./flash1.php

  gpio:
    image: jgivoni/rpi-gpio-server:latest
    devices:
    - /dev/gpiomem
