version: '3.2'
# This file is not in use if docker-compose could not be installed on the raspberry (e.g. model 1)

services:
  gpio:
    image: jgivoni/rpi-gpio-server:4
    container_name: gpio
    devices:
      - /dev/gpiomem
    privileged: true # Needed for PWM
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  welcomepi:
    image: welcomepi:latest
    container_name: app
    build: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    links:
      - gpio
    restart: unless-stopped
    depends_on:
      - gpio
    logging:
      options:
        max-size: "10m"
        max-file: "3"

#  composer:
#    image: composer
#    command: composer update --ignore-platform-reqs
#    volumes:
#      - .:/app
