version: '3.2'

services:
  gpio:
    image: jgivoni/rpi-gpio-server:4
    container_name: gpio
    devices:
      - /dev/gpiomem
    privileged: true # Needed for PWM
    restart: unless-stopped

  welcomepi:
    image: welcomepi:latest
    container_name: app
    build: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    links:
      - gpio
    restart: unless-stopped
    depends_on:
      - gpio

#  composer:
#    image: composer
#    command: composer update --ignore-platform-reqs
#    volumes:
#      - .:/app
