version: '3.2'

services:
  welcomepi:
    image: welcomepi:latest
    build: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    links:
      - gpio
    restart: unless-stopped

  gpio:
    image: jgivoni/rpi-gpio-server:latest
    devices:
      - /dev/gpiomem
    privileged: true # Needed for PWM
    restart: unless-stopped

#  composer:
#    image: composer
#    command: composer update --ignore-platform-reqs
#    volumes:
#      - .:/app
